name: Rust XMR Miner Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_mine:
    # تم التعديل هنا للعمل مباشرة على سيرفرات GitHub السحابية
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-miner
          
      - name: Build Miner 🛠️
        run: |
          echo "🛠️ جاري بناء كود التعدين بوضع الـ Release..."
          cargo build --release

      - name: Run Miner 🚀
        continue-on-error: true 
        run: |
          echo "🚀 جاري تشغيل المُعدّن..."
          chmod +x ./target/release/xmr_rust_miner
          ./target/release/xmr_rust_miner
